export const data = {
  colors: [
    'Aquamarine',
    'Beige',
    'Black',
    'Blue',
    'Brown',
    'Cherry',
    'Cream',
    'Emerald',
    'Fuchsia',
    'Golden',
    'Green',
    'Grey',
    'Light blue',
    'Lilac',
    'Maroon',
    'Olive',
    'Orange',
    'Pink',
    'Purple',
    'Raspberry',
    'Red',
    'Sandy',
    'Silver',
    'Turquoise',
    'Violet',
    'White',
    'Yellow',
  ],
  sizes: [
    30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
    49, 50,
  ],
  genders: ['Female', 'Male'],
  categories: [
    'Blouses and shirts',
    'Pants',
    'Outerwear',
    'Sweater, turtlenecks, cardigans',
    'Jeans',
    'Overalls',
    'Suits',
    'Longsleeves',
    'Jackets, vests, jackets',
    'Dresses and sundresses',
  ],
  brands: ['Chanel', 'Louis Vuitton'],
  sellers: ['Koleso', 'New Yorker'],
  compositions: [
    'Cotton',
    'Polyester',
    'Nylon',
    'Wool',
    'Silk',
    'Rayon',
    'Linen',
    'Cashmere',
    'Modal',
    'Spandex',
    'Acrylic',
    'Viscose',
    'Bamboo',
    'Denim',
    'Fleece',
    'Satin',
    'Tweed',
    'Velvet',
    'Leather',
    'Faux Leather',
    'Suede',
    'Synthetic',
    'Lycra',
    'Chiffon',
    'Lace',
    'Microfiber',
    'Jersey',
  ],
  wheatherConditions: ['Wind', 'Sun', 'Snow', 'Rain'],
};
